- name: Push config down the device
  block:
    - name: create config folder
      file:
        path: "{{ conf_dir }}/final_config"
        state: directory

    - name: Assembling configurations and copying to conf/
      assemble: src={{ conf_dir }}/build_config dest={{ conf_dir }}/final_config/combined_config.conf

    - name: Set the final config file name
      set_fact:
        source_file: "{{ conf_dir }}/final_config/combined_config.conf"

    - name: Load final config be deployed to device
      set_fact:
        contents: "{{ lookup('file', '{{source_file}}')}}"

    - name: print final config
      debug: var = {{contents}} verbosity=1

    - name: Update job log with percentage
      include_tasks: percentage_update.yml
      vars:
        current_index: 1
        jl_message: "Deploying following config to device '{{ device_name }}'(it may take a while)\n{{ contents }}"
  when: set_device_mode is undefined or not set_device_mode

- name: finish with vendor-specific commit logic
  include_tasks: "{{ device_vendor }}.yml"

- name: print device response
  debug: msg="{{ device_push_response }}" verbosity=1

- name: Update job log with percentage
  include_tasks: percentage_update.yml
  vars:
    current_index: 2
    jl_message: "{{ device_push_message }}"
  when: set_device_mode is undefined or not set_device_mode

